---
- name: Updating RedHat Linux Distribution
  ansible.builtin.import_tasks: RedHat.yml
  when: "ansible_os_family == 'RedHat'"
- name: Updating Debian Based Linux Distribution
  ansible.builtin.import_tasks: Debian.yml
  when: "ansible_os_family == 'Debian'"
...
