---
- name: Updating and install Debian Packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
    autoremove: true
  environment: "{{ proxy_env | default({}) }}"
...
