---
- name: Updating Debian Packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
    cache_valid_time: 3600
    autoremove: true
  environment: "{{ proxy_env | default({}) }}"
...
