---
  - name: Pre Install and Config Repo by shell script.
    # You Can Find Script Here:
    # https://docs.gitlab.com/runner/install/linux-repository.html
    shell: curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | bash

  - name: installing gitlab-runner in Debian
    apt:
      name: gitlab-runner
      update_cache: "{{ UPDATE_CACHE }}"