---

OS_ARCH: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
PACKAGE: "{{ (ansible_os_family == 'RedHat') | ternary('rpm','deb') }}"

GITLAB_RUNNER_BASE_URL: "https://gitlab-runner-downloads.s3.amazonaws.com/latest/{{ PACKAGE }}"
GITLAB_RUNNER_ARCH_URL: "gitlab-runner_{{ OS_ARCH }}.{{ PACKAGE }}"
GITLAB_RUNNER_URL: "{{ GITLAB_RUNNER_BASE_URL }}/{{ GITLAB_RUNNER_ARCH_URL }}"

GITLAB_RUNNER_STATE: present
UPDATE_CACHE: true

GITLAB_REPO_CONFIG: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/config_file.{{ (ansible_os_family == 'RedHat') | ternary('repo','list') }}"
GITLAB_YUM_REPO_CONFIG_URL: "{{ GITLAB_REPO_CONFIG }}?os={{ ansible_distribution | lower }}&dist={{ ansible_distribution_major_version }}&source=script"
YUM_REPO_PATH: "/etc/yum.repos.d/runner_gitlab-runner.repo"
KEY_STATE: present

# Grab GPG Key from Here if it Changed in future:
# https://docs.gitlab.com/runner/install/linux-repository.html
GITLAB_YUM_GPG_KEY_URL: "https://packages.gitlab.com/runner/gitlab-runner/gpgkey/runner-gitlab-runner-49F16C5CC3A0F81F.pub.gpg"