---
- name: User | Delete User
  ansible.builtin.user:
    name: "{{ user.name }}"
    state: absent
    remove: true
    force: true
  tags:
    - delete_user
    - delete_user_group

- name: User | Delete User Group
  ansible.builtin.group:
    name: "{{ (user.group is defined and user.group | length > 0) | ternary(user.group, user.name) }}"
    state: absent
    force: true
  tags:
    - delete_group
    - delete_user_group
...
