---
# Default configuration for user management
user:
  # group: "random-user-group"
  system: false
  name: "random-user"
  comment: "Random User"
  create_home: true

  # comment the `home`, If home dir is not default /home/user.name
  home: "/home/random-home-user"
  shell: "/bin/bash"
  sudoer: false
  append: true
  state: present
  password: "P4SSW0rd"

user_groups:
  - "{{ ('wheel' if ansible_os_family == 'RedHat' else 'sudo') if user.sudoer else '' }}"
user_new_password: ""
user_ssh_key_path: "{{ lookup('file', '/path/to/home/user/.ssh/ssh-key.pub') }}"
