---
# Default configuration for user management
user:
  group: ""
  # If User is not system user , comment the `system`
  # It uses for both group and user
  system: ""
  name: ""
  comment: ""
  create_home: true
  # If User doesn't need to have home directory other than the default /home/user.name
  # comment the `home`
  home: ""
  shell: "/bin/bash"
  sudoer: false
  append: true
  state: present
  password: ""

# Define user_groups with conditional group for sudo/wheel
user_groups:
  - "{{ 'wheel' if ansible_os_family == 'RedHat' else 'sudo' if user.sudoer else '' }}"

user_new_password: ""

user_ssh_key_path: "{{ lookup('file', '/home/ali/.ssh/id_ed25519.pub') }}"
