---
- name: Creating User "{{ USER_NAME }}" ...
  ansible.builtin.user:
    name: "{{ USER_NAME }}"
    comment: "{{ COMMENT }}"
    shell: "{{ USER_SHELL }}"
    state: present
    password: "{{ USER_PASSWORD | password_hash('sha512') }}"
    groups:
      - "{{ 'wheel' if ansible_os_family == 'RedHat' else 'sudo' }}"
    append: true
  tags:
    - create_user
...
