---
- name: Creating User "{{ user_name }}" ...
  ansible.builtin.user:
    name: "{{ user_name }}"
    comment: "{{ user_comment }}"
    shell: "{{ user_shell }}"
    state: present
    password: "{{ user_password | password_hash('sha512') }}"
    groups:
      - "{{ 'wheel' if ansible_os_family == 'RedHat' else 'sudo' }}"
    append: true
...
