---
  - name: Updating User "{{ USER_NAME }}" Password
    ansible.builtin.user:
      name: "{{ USER_NAME }}"
      update_password: always
      password: "{{ NEW_PASSWORD | password_hash('sha512') }}"
    tags:
      - update_password

