---
  - name: Updateing User "{{ USER_NAME }}" Password
    user:
      name: "{{ USER_NAME }}"
      update_password: always
      password: "{{ NEW_PASSWORD | password_hash('sha512') }}"
    tags:
      - update_password